require: rubocop-bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.1.2

  Exclude:
    - .gitignore
    - .rubocop.yml

    - Gemfile.lock
    - CHANGELOG.md
    - LICENSE.txt
    - README.md
    - Rakefile
    - bridgetown.automation.rb

    - node_modules/**/*
    - script/**/*
    - vendor/**/*
